name: gestion_immobiliere
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.0
  provider: ^6.1.2
  google_sign_in: ^6.2.3
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.3.4
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  
  # Ajout de la localisation GPS
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
